df = read.csv("/Users/kolbesurran/Desktop/4375/Project_One/titanic_project.csv")
head(df)
summary(df)
cor(df)
colSums(is.na(df))
sum(is.na(df$age))
par(mfrow=c(2,2))
df$pclass <- as.factor(df$pclass)
df$survived <- as.factor(df$survived)
df$sex <- as.factor(df$sex)
plot(df$survived,df$pclass, xlab="Survive", ylab="Class", main="Class vs. Survived")
plot(df$survived, df$sex, xlab = "Survived", ylab="Sex", main="Sex vs. Survived")
plot(df$pclass, df$X, xlab = "PClass", ylab="X", main="X vs PClass")
plot(df$pclass, df$age, xlab = "PClass", ylab="Age", main="Age vs PClass")
train <- df[1:900,]
test <- df[900:nrow(df),]
start <- Sys.time()
glm0 <- glm(survived~pclass,data=train,family=binomial)
end <- Sys.time()
summary(glm0)
p <- predict(glm0, newdata = test, type="response")
pred <- ifelse(p>.5, 1,0)
confusionMatrix(as.factor(pred), test$survived, positive = "1")
training_time <- end - start
paste("training time duration in seconds:",training_time)
